import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Buffer} from 'node:buffer';
const index=await readFile(new URL('../index.html',import.meta.url),'utf8');
const panel=await readFile(new URL('../panel.html',import.meta.url),'utf8');
const sw=await readFile(new URL('../sw.js',import.meta.url),'utf8');
assert.match(index,/if\(CONFIG\.pwaEnabled\)\{/);
assert.match(index,/getRegistrations\(\)\.then/);
assert.doesNotMatch(index,/<link rel=\"manifest\" href=\"manifest\.json\">/);
assert.match(panel,/if\(publishCfg\.pwaEnabled !== false\)/);
assert.match(panel,/sha:null/);
assert.match(panel,/function renderSection\(id, markDirty=false\)/);
assert.match(panel,/PUBLISH_VERSION = 'V11\.3'/);
assert.match(sw,/v11\.3/);
const m=panel.match(/const BASE_TEMPLATE_B64 = "([^"]+)";/);
assert.ok(m);
assert.equal(Buffer.from(m[1],'base64').toString('utf8'),index);
assert.match(index,/feeLabel/);
assert.match(index,/payment\.name/);
assert.match(index,/cryptoAsset\?\.name/);
assert.match(index,/Coupon PCS/);
assert.match(index,/Paysafecard/);
console.log('V11.3 coherence tests: OK');
